/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulaire;

import Entite.Commande;
import Exception.DateFormatException;
import dao.ServiceCommande;
import static java.lang.Integer.parseInt;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author adral
 */
public class JFCommande extends javax.swing.JFrame {

    /**
     * Creates new form JFCommande
     */
    public JFCommande() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCTextFieldRefCommande = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jCTextFieldQteProd = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jCTextFieldMontant = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jCTextFieldDateCommande = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jCTextFieldDateRecuCommande = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangleFermer = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleValider = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleAnnuler = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/commande1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 610, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enregistrement de commande");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ref Commande");

        jCTextFieldRefCommande.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldRefCommande.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldRefCommande.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldRefCommande.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRefCommande.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRefCommande.setPlaceholder("Reference de la commande");
        jCTextFieldRefCommande.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qte_Prod");

        jCTextFieldQteProd.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldQteProd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldQteProd.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldQteProd.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldQteProd.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldQteProd.setPlaceholder("entrez la quantité commandé");
        jCTextFieldQteProd.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Montant");

        jCTextFieldMontant.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldMontant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldMontant.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setPlaceholder("Montant TTC");
        jCTextFieldMontant.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Commande");

        jCTextFieldDateCommande.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldDateCommande.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldDateCommande.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldDateCommande.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldDateCommande.setPlaceholder("JJ/MM/AAAA");
        jCTextFieldDateCommande.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date reçu commande");

        jCTextFieldDateRecuCommande.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldDateRecuCommande.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldDateRecuCommande.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldDateRecuCommande.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldDateRecuCommande.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldDateRecuCommande.setPlaceholder("JJ/MM/AAAA");
        jCTextFieldDateRecuCommande.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        rSMaterialButtonRectangleFermer.setBackground(new java.awt.Color(153, 0, 51));
        rSMaterialButtonRectangleFermer.setText("Fermer");
        rSMaterialButtonRectangleFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleFermerActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleValider.setBackground(new java.awt.Color(0, 153, 153));
        rSMaterialButtonRectangleValider.setText("Enregistrer");
        rSMaterialButtonRectangleValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleValiderActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleAnnuler.setBackground(new java.awt.Color(102, 0, 255));
        rSMaterialButtonRectangleAnnuler.setText("Annuler");
        rSMaterialButtonRectangleAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleAnnulerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCTextFieldRefCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCTextFieldQteProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jCTextFieldMontant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCTextFieldDateCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCTextFieldDateRecuCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rSMaterialButtonRectangleValider, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rSMaterialButtonRectangleAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rSMaterialButtonRectangleFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(133, 133, 133)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldRefCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCTextFieldQteProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCTextFieldDateCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldDateRecuCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMaterialButtonRectangleValider, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 420, 620));

        setSize(new java.awt.Dimension(1202, 618));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangleFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangleFermerActionPerformed

    private void rSMaterialButtonRectangleAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleAnnulerActionPerformed
        // TODO add your handling code here:
         int userchoice=JOptionPane.showConfirmDialog(rootPane,"Voulez-vous effacer tout ce qu'il y a dans les champs?", "Information message", JOptionPane.YES_NO_OPTION);
         if(userchoice==0){
             jCTextFieldRefCommande.setText(null);
             jCTextFieldRefCommande.requestFocus();
             jCTextFieldQteProd.setText(null);
             jCTextFieldMontant.setText(null);
             jCTextFieldDateCommande.setText(null);
             jCTextFieldDateRecuCommande.setText(null);
         }
    }//GEN-LAST:event_rSMaterialButtonRectangleAnnulerActionPerformed

    private void rSMaterialButtonRectangleValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleValiderActionPerformed
        // TODO add your handling code here:
        Commande cde2=new Commande();
        if(jCTextFieldRefCommande.getText().length()>0){
            cde2.setRef_commande(jCTextFieldRefCommande.getText());
        }
        if(jCTextFieldQteProd.getText().length()>0){
            try{
                cde2.setQte_prod(parseInt(jCTextFieldQteProd.getText()));
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane,"Vous devez mettre des entiers","Error Message",JOptionPane.ERROR_MESSAGE);
            }           
        }
        if(jCTextFieldMontant.getText().length()>0){
            try{
                cde2.setMontant(parseInt(jCTextFieldMontant.getText()));
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane,"Vous devez mettre des entiers","Error Message",JOptionPane.ERROR_MESSAGE);
            }          
        }
        if(jCTextFieldDateCommande.getText().length()>0){
            cde2.setDate_commande(jCTextFieldDateCommande.getText());
        }
        if(jCTextFieldDateRecuCommande.getText().length()>0){
            cde2.setDate_recu_commande(jCTextFieldDateRecuCommande.getText());
        }
        int retour=ServiceCommande.SaveCommande(cde2);
        if(retour==0){
            JOptionPane.showMessageDialog(rootPane, "verifier les saisies erreur","Error message",JOptionPane.ERROR_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "enregistrement effectué avec succès! ","Information message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_rSMaterialButtonRectangleValiderActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCommande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextFieldDateCommande;
    private app.bolivia.swing.JCTextField jCTextFieldDateRecuCommande;
    private app.bolivia.swing.JCTextField jCTextFieldMontant;
    private app.bolivia.swing.JCTextField jCTextFieldQteProd;
    private app.bolivia.swing.JCTextField jCTextFieldRefCommande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleAnnuler;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleFermer;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleValider;
    // End of variables declaration//GEN-END:variables
}
