/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulaire;

import Entite.Commande;
import Entite.Facture;
import dao.ServiceCommande;
import dao.ServiceFacture;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author adral
 */
public class JFFacture extends javax.swing.JFrame {

    /**
     * Creates new form JFFacture
     */
    public JFFacture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCTextFieldRefFacture = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jCTextFieldProduitAchete = new app.bolivia.swing.JCTextField();
        jCTextFieldMontant = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCTextFieldNomFournisseur = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangleFermer = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleAnnuler = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleValider = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/istockphoto-1284067597-612x612.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 580, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 620));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enregistrement facture");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ref Facture");

        jCTextFieldRefFacture.setBackground(new java.awt.Color(0, 102, 204));
        jCTextFieldRefFacture.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldRefFacture.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRefFacture.setPlaceholder("Reférence facture");
        jCTextFieldRefFacture.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Produit acheté");

        jCTextFieldProduitAchete.setBackground(new java.awt.Color(0, 102, 204));
        jCTextFieldProduitAchete.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldProduitAchete.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldProduitAchete.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldProduitAchete.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldProduitAchete.setPlaceholder("Type de produit Acheté");

        jCTextFieldMontant.setBackground(new java.awt.Color(0, 102, 204));
        jCTextFieldMontant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldMontant.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setPlaceholder("Montant TTC");
        jCTextFieldMontant.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Montant");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nom Fournisseur");

        jCTextFieldNomFournisseur.setBackground(new java.awt.Color(0, 102, 204));
        jCTextFieldNomFournisseur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldNomFournisseur.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldNomFournisseur.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldNomFournisseur.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldNomFournisseur.setPlaceholder("Nom du fournisseur");
        jCTextFieldNomFournisseur.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        rSMaterialButtonRectangleFermer.setBackground(new java.awt.Color(102, 0, 51));
        rSMaterialButtonRectangleFermer.setText("Fermer");
        rSMaterialButtonRectangleFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleFermerActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleAnnuler.setBackground(new java.awt.Color(51, 51, 0));
        rSMaterialButtonRectangleAnnuler.setText("Annuler");
        rSMaterialButtonRectangleAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleAnnulerActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleValider.setBackground(new java.awt.Color(0, 102, 102));
        rSMaterialButtonRectangleValider.setText("valider");
        rSMaterialButtonRectangleValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleValiderActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCTextFieldRefFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(27, 27, 27)
                                    .addComponent(jCTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCTextFieldProduitAchete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCTextFieldNomFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSMaterialButtonRectangleValider, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSMaterialButtonRectangleAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSMaterialButtonRectangleFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldRefFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldProduitAchete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldNomFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMaterialButtonRectangleFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleValider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 430, 620));

        setSize(new java.awt.Dimension(1070, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangleValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleValiderActionPerformed
        // TODO add your handling code here:
        Facture cde2=new Facture();
        if(jCTextFieldRefFacture.getText().length()>0){
            cde2.setRef_facture(jCTextFieldRefFacture.getText());
        }
        if(jCTextFieldProduitAchete.getText().length()>0){
            
                cde2.setProduits(jCTextFieldProduitAchete.getText());                    
        }
        if(jCTextFieldNomFournisseur.getText().length()>0){
            cde2.setNomFournisseur(jCTextFieldNomFournisseur.getText());
        }
        if(jCTextFieldMontant.getText().length()>0){
            try{
                cde2.setMontant(parseInt(jCTextFieldMontant.getText()));
                int retour=ServiceFacture.SaveFacture(cde2);
                if(retour==0){
                    JOptionPane.showMessageDialog(rootPane, "verifier les saisies erreur","Error message",JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "enregistrement effectué avec succès! ","Information message",JOptionPane.INFORMATION_MESSAGE);
            }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane,"Vous devez mettre des entiers","Error Message",JOptionPane.ERROR_MESSAGE);
                
            }           
        }
        
        
        
    }//GEN-LAST:event_rSMaterialButtonRectangleValiderActionPerformed

    private void rSMaterialButtonRectangleAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleAnnulerActionPerformed
        // TODO add your handling code here:
        int userchoice=JOptionPane.showConfirmDialog(rootPane,"Voulez-vous effacer tout ce qu'il y a dans les champs?", "Information message", JOptionPane.YES_NO_OPTION);
         if(userchoice==0){
             jCTextFieldRefFacture.setText(null);
             jCTextFieldRefFacture.requestFocus();
             jCTextFieldNomFournisseur.setText(null);
             jCTextFieldMontant.setText(null);
            
             jCTextFieldProduitAchete.setText(null);
         }
    }//GEN-LAST:event_rSMaterialButtonRectangleAnnulerActionPerformed

    private void rSMaterialButtonRectangleFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangleFermerActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFacture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextFieldMontant;
    private app.bolivia.swing.JCTextField jCTextFieldNomFournisseur;
    private app.bolivia.swing.JCTextField jCTextFieldProduitAchete;
    private app.bolivia.swing.JCTextField jCTextFieldRefFacture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleAnnuler;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleFermer;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleValider;
    // End of variables declaration//GEN-END:variables
}
