/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulaire;

import Entite.Commande;
import Entite.Produit;
import dao.ServiceClient;
import dao.ServiceCommande;
import dao.ServiceProduit;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author adral
 */
public class JFModifSupCommande extends javax.swing.JFrame {

    /**
     * Creates new form JFModifSupCommande
     */
    public JFModifSupCommande() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCTextFieldRecherche = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangleModifier = new rojerusan.RSMaterialButtonRectangle();
        jCTextFieldidCommande = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCTextFieldRefCommande = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jCTextFieldQuantiteProduit = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jCTextFieldMontant = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jCTextFieldDateCommande = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangleRecherche = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleFermer = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleSupprimer = new rojerusan.RSMaterialButtonRectangle();
        jLabel8 = new javax.swing.JLabel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/commande1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 38, 563, 539));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 630));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recherche Modification et suppression des commandes");

        jCTextFieldRecherche.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldRecherche.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldRecherche.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setPlaceholder("Recherche par ref_commande");
        jCTextFieldRecherche.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        rSMaterialButtonRectangleModifier.setBackground(new java.awt.Color(0, 102, 0));
        rSMaterialButtonRectangleModifier.setText("Modifier");
        rSMaterialButtonRectangleModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleModifierActionPerformed(evt);
            }
        });

        jCTextFieldidCommande.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldidCommande.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldidCommande.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldidCommande.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldidCommande.setEnabled(false);
        jCTextFieldidCommande.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldidCommande.setPlaceholder("id commande");
        jCTextFieldidCommande.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("id commande");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ref commande");

        jCTextFieldRefCommande.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldRefCommande.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldRefCommande.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldRefCommande.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRefCommande.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRefCommande.setPlaceholder("Reference de la commande");
        jCTextFieldRefCommande.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("qte produit");

        jCTextFieldQuantiteProduit.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldQuantiteProduit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldQuantiteProduit.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldQuantiteProduit.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldQuantiteProduit.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldQuantiteProduit.setPlaceholder("quantite de produit");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Montant");

        jCTextFieldMontant.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldMontant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldMontant.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldMontant.setPlaceholder("Montant de la commande");
        jCTextFieldMontant.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Commande");

        jCTextFieldDateCommande.setBackground(new java.awt.Color(0, 102, 153));
        jCTextFieldDateCommande.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldDateCommande.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldDateCommande.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldDateCommande.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldDateCommande.setPlaceholder("JJ/MM/AAAA");
        jCTextFieldDateCommande.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        rSMaterialButtonRectangleRecherche.setBackground(new java.awt.Color(153, 0, 102));
        rSMaterialButtonRectangleRecherche.setText("Rechercher");
        rSMaterialButtonRectangleRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleRechercheActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleFermer.setBackground(new java.awt.Color(153, 0, 51));
        rSMaterialButtonRectangleFermer.setText("Fermer");
        rSMaterialButtonRectangleFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleFermerActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleSupprimer.setBackground(new java.awt.Color(51, 0, 51));
        rSMaterialButtonRectangleSupprimer.setText("Supprimer");
        rSMaterialButtonRectangleSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleSupprimerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date reçu commande");

        jCTextField1.setBackground(new java.awt.Color(0, 102, 153));
        jCTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField1.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField1.setPlaceholder("JJ/MM/AAAA");
        jCTextField1.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCTextFieldQuantiteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCTextFieldidCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCTextFieldRefCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rSMaterialButtonRectangleModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rSMaterialButtonRectangleSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rSMaterialButtonRectangleFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCTextFieldDateCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(269, Short.MAX_VALUE)
                    .addComponent(rSMaterialButtonRectangleRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(69, 69, 69)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCTextFieldidCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCTextFieldRefCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldQuantiteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCTextFieldDateCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMaterialButtonRectangleModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(rSMaterialButtonRectangleRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(451, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 460, 630));

        setSize(new java.awt.Dimension(1062, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangleRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleRechercheActionPerformed
        // TODO add your handling code here:
        if(jCTextFieldRecherche.getText().length()>0){
           Commande cde=ServiceCommande.ReadCommande(jCTextFieldRecherche.getText());
           if(cde.getId_commande()==0){
               JOptionPane.showMessageDialog(rootPane,"Commande non trouvé","information message", JOptionPane.INFORMATION_MESSAGE);
           }else{
               jCTextFieldidCommande.setText(String.valueOf(cde.getId_commande()));
               jCTextFieldRefCommande.setText(cde.getRef_commande());
               jCTextFieldQuantiteProduit.setText(String.valueOf(cde.getQte_prod()));
               jCTextFieldMontant.setText(String.valueOf(cde.getMontant()));
               jCTextFieldDateCommande.setText(cde.getDate_commande());
               
               jCTextField1.setText(cde.getDate_recu_commande());
           }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Le champs de recherche ne peut pas être nul si vous chercher les informations sur un Client.","Error Message",JOptionPane.ERROR_MESSAGE);
            jCTextFieldRecherche.requestFocus();
        }
    }//GEN-LAST:event_rSMaterialButtonRectangleRechercheActionPerformed

    private void rSMaterialButtonRectangleFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangleFermerActionPerformed

    private void rSMaterialButtonRectangleModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleModifierActionPerformed
        // TODO add your handling code here:
         Commande cdd1=new Commande();
        if(jCTextFieldidCommande.getText().length()>0){
            cdd1.setId_commande(parseInt(jCTextFieldidCommande.getText()));
        }
        if(jCTextFieldRefCommande.getText().length()>0){
            cdd1.setRef_commande(jCTextFieldRefCommande.getText());
        }
        if(jCTextFieldQuantiteProduit.getText().length()>0){
            cdd1.setQte_prod(parseInt(jCTextFieldQuantiteProduit.getText()));
        }
        if(jCTextFieldMontant.getText().length()>0){
            cdd1.setMontant(parseInt(jCTextFieldMontant.getText()));
        }
        if(jCTextFieldDateCommande.getText().length()>0){
            cdd1.setDate_commande(jCTextFieldDateCommande.getText());
        }
        if(jCTextField1.getText().length()>0){
            cdd1.setDate_recu_commande(jCTextField1.getText());
        }
        int resultat=ServiceCommande.UpdateCommande(cdd1);
        if(resultat==0){
            JOptionPane.showMessageDialog(rootPane,"Erreur de modification un probleme est surevenu!");
        }else{
            JOptionPane.showMessageDialog(rootPane,"Modification effectué avec succés");
        }
        
    }//GEN-LAST:event_rSMaterialButtonRectangleModifierActionPerformed

    private void rSMaterialButtonRectangleSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleSupprimerActionPerformed
        // TODO add your handling code here:
         if(jCTextFieldRecherche.getText().length()>0){
            int retour1=JOptionPane.showConfirmDialog(rootPane,"Voulez-vous réellement supprimer cet commande?","Confirmation Message",JOptionPane.YES_NO_OPTION);
            if(retour1==0){
                int retour =ServiceCommande.DeleteCommande(jCTextFieldRecherche.getText());
                if(retour==0){
                    JOptionPane.showMessageDialog(rootPane,"Erreur sql revoir les parametres de la methode delete et l'execution","Warning message",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Commande supprimer!","Information Message",JOptionPane.INFORMATION_MESSAGE);
                    jCTextFieldRecherche.setText(null);
                    jCTextFieldRefCommande.setText(null);
                    jCTextFieldQuantiteProduit.setText(null);
                    jCTextFieldMontant.setText(null);
                    jCTextFieldDateCommande.setText(null);
                    jCTextField1.setText(null);
                    jCTextFieldRecherche.requestFocus();
                    
                }
            }    
        }else{
            JOptionPane.showMessageDialog(rootPane, "vous ne pouvez pas rechercher quelque chose que vous n'avez pas demander autrement dit veuillez fournir les le nom pour la recherche du client","Information Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_rSMaterialButtonRectangleSupprimerActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModifSupCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModifSupCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModifSupCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModifSupCommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModifSupCommande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextField1;
    private app.bolivia.swing.JCTextField jCTextFieldDateCommande;
    private app.bolivia.swing.JCTextField jCTextFieldMontant;
    private app.bolivia.swing.JCTextField jCTextFieldQuantiteProduit;
    private app.bolivia.swing.JCTextField jCTextFieldRecherche;
    private app.bolivia.swing.JCTextField jCTextFieldRefCommande;
    private app.bolivia.swing.JCTextField jCTextFieldidCommande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleFermer;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleModifier;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleRecherche;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleSupprimer;
    // End of variables declaration//GEN-END:variables
}
