/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulaire;

import Entite.Client;
import dao.ServiceClient;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author adral
 */
public class JFModifSupClient extends javax.swing.JFrame {

    /**
     * Creates new form JFModifSupClient
     */
    public JFModifSupClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCTextFieldRecherche = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jCTextFieldNomCLient = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jCTextFieldPrenomClient = new app.bolivia.swing.JCTextField();
        jCTextFieldAdresseClient = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        rSMaterialButtonRectangleModifier = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleFermerFnetre = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangledelete = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleRecherche = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        jCTextFieldId_client = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/undraw_building_websites_i78t.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 31, 886, 682));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recherche/Modification Client");

        jCTextFieldRecherche.setBackground(new java.awt.Color(102, 102, 255));
        jCTextFieldRecherche.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        jCTextFieldRecherche.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setPlaceholder("entre un nom pour la recherche");
        jCTextFieldRecherche.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom Client");

        jCTextFieldNomCLient.setBackground(new java.awt.Color(102, 102, 255));
        jCTextFieldNomCLient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextFieldNomCLient.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldNomCLient.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldNomCLient.setPlaceholder("Nom client");
        jCTextFieldNomCLient.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prenom");

        jCTextFieldPrenomClient.setBackground(new java.awt.Color(102, 102, 255));
        jCTextFieldPrenomClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextFieldPrenomClient.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldPrenomClient.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldPrenomClient.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldPrenomClient.setPlaceholder("Prenom client");
        jCTextFieldPrenomClient.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jCTextFieldAdresseClient.setBackground(new java.awt.Color(102, 102, 255));
        jCTextFieldAdresseClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextFieldAdresseClient.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldAdresseClient.setPlaceholder("Adresse Client");
        jCTextFieldAdresseClient.setSelectedTextColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Adresse");

        rSMaterialButtonRectangleModifier.setBackground(new java.awt.Color(0, 51, 51));
        rSMaterialButtonRectangleModifier.setText("Modifier");
        rSMaterialButtonRectangleModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleModifierActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleFermerFnetre.setBackground(new java.awt.Color(0, 51, 51));
        rSMaterialButtonRectangleFermerFnetre.setText("Fermer");
        rSMaterialButtonRectangleFermerFnetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleFermerFnetreActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangledelete.setBackground(new java.awt.Color(0, 51, 51));
        rSMaterialButtonRectangledelete.setText("Supprimer");
        rSMaterialButtonRectangledelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangledeleteActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangleRecherche.setBackground(new java.awt.Color(51, 0, 0));
        rSMaterialButtonRectangleRecherche.setText("Rechercher");
        rSMaterialButtonRectangleRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleRechercheActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id_client");

        jCTextFieldId_client.setBackground(new java.awt.Color(102, 102, 255));
        jCTextFieldId_client.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextFieldId_client.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldId_client.setEnabled(false);
        jCTextFieldId_client.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldId_client.setPlaceholder("Identifiant du client");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCTextFieldId_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCTextFieldPrenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCTextFieldAdresseClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCTextFieldNomCLient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSMaterialButtonRectangleRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(rSMaterialButtonRectangleModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(rSMaterialButtonRectangledelete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rSMaterialButtonRectangleFermerFnetre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCTextFieldId_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jCTextFieldNomCLient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCTextFieldPrenomClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCTextFieldAdresseClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMaterialButtonRectangleModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangledelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangleFermerFnetre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1325, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rSMaterialButtonRectangleModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleModifierActionPerformed
        // TODO add your handling code here:
        Client cl1=new Client();
            cl1.setId_client(parseInt(jCTextFieldId_client.getText()));
            cl1.setNom_client(jCTextFieldNomCLient.getText());
            cl1.setPrenom_client(jCTextFieldPrenomClient.getText());
            cl1.setAdresse_client(jCTextFieldAdresseClient.getText());
        int retourDeMethode=ServiceClient.UpdateClient(cl1);
        if(retourDeMethode==0){
            JOptionPane.showMessageDialog(rootPane,"Erreur de modification un probleme est surevenu!");
        }else{
            JOptionPane.showMessageDialog(rootPane,"Modification effectué avec succés");
        }
        
    }//GEN-LAST:event_rSMaterialButtonRectangleModifierActionPerformed

    private void rSMaterialButtonRectangleRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleRechercheActionPerformed
        // TODO add your handling code here:
        if(jCTextFieldRecherche.getText().length()>0){
            Client Marc=ServiceClient.ReadClient(jCTextFieldRecherche.getText());
            //String id=String.valueOf(Marc.getId_client());
            if(Marc.getId_client()==0){
                JOptionPane.showMessageDialog(null,"Personne non-trouvé");
            }
            else{
                jCTextFieldId_client.setText(String.valueOf(Marc.getId_client()));
                jCTextFieldNomCLient.setText(Marc.getNom_client());
                jCTextFieldPrenomClient.setText(Marc.getPrenom_client());
                jCTextFieldAdresseClient.setText(Marc.getAdresse_client());
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Le champs de recherche ne peut pas être nul si vous chercher les informations sur un Client.","Error Message",JOptionPane.ERROR_MESSAGE);
            jCTextFieldRecherche.requestFocus();
        }
    }//GEN-LAST:event_rSMaterialButtonRectangleRechercheActionPerformed

    private void rSMaterialButtonRectangledeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangledeleteActionPerformed
        // TODO add your handling code here:
        if(jCTextFieldRecherche.getText().length()>0){
            int retour1=JOptionPane.showConfirmDialog(rootPane,"Voulez-vous réellement supprimer cet client?","Confirmation Message",JOptionPane.YES_NO_OPTION);
            if(retour1==0){
                int retour =ServiceClient.DeleteClient(jCTextFieldRecherche.getText());
                if(retour==0){
                    JOptionPane.showMessageDialog(rootPane,"Erreur sql revoir les parametres de la methode delete et l'execution","Warning message",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Client supprimer!","Information Message",JOptionPane.INFORMATION_MESSAGE);
                    jCTextFieldRecherche.setText(null);
                    jCTextFieldAdresseClient.setText(null);
                    jCTextFieldNomCLient.setText(null);
                    jCTextFieldId_client.setText(null);
                    jCTextFieldRecherche.setText(null);
                    jCTextFieldPrenomClient.setText(null);
                }
            }
           
        }else{
            JOptionPane.showMessageDialog(rootPane, "vous ne pouvez pas rechercher quelque chose que vous n'avez pas demander autrement dit veuillez fournir les le nom pour la recherche du client","Information Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_rSMaterialButtonRectangledeleteActionPerformed

    private void rSMaterialButtonRectangleFermerFnetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleFermerFnetreActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangleFermerFnetreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModifSupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModifSupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModifSupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModifSupClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModifSupClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextFieldAdresseClient;
    private app.bolivia.swing.JCTextField jCTextFieldId_client;
    private app.bolivia.swing.JCTextField jCTextFieldNomCLient;
    private app.bolivia.swing.JCTextField jCTextFieldPrenomClient;
    private app.bolivia.swing.JCTextField jCTextFieldRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleFermerFnetre;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleModifier;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleRecherche;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangledelete;
    // End of variables declaration//GEN-END:variables
}
