/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulaire;

import Entite.Produit;
import dao.ServiceProduit;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author adral
 */
public class JFModifSupProduit extends javax.swing.JFrame {

    /**
     * Creates new form JFModifSupProduit
     */
    public JFModifSupProduit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCTextFieldIdproduit = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        jCTextFieldNomProduit = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jCTextFieldQuantite = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangleFermer = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleModifier = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangleSupprimer = new rojerusan.RSMaterialButtonRectangle();
        jLabel6 = new javax.swing.JLabel();
        jCTextFieldRecherche = new app.bolivia.swing.JCTextField();
        rSMaterialButtonRectangleRecherche = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/pc.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, 588, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 620));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recherche/Modification");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id_prod");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 63, -1));

        jCTextFieldIdproduit.setBackground(new java.awt.Color(51, 0, 102));
        jCTextFieldIdproduit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldIdproduit.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldIdproduit.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldIdproduit.setPlaceholder("id client");
        jCTextFieldIdproduit.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jCTextFieldIdproduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nom Produit");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jCTextFieldNomProduit.setBackground(new java.awt.Color(51, 0, 102));
        jCTextFieldNomProduit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldNomProduit.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldNomProduit.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldNomProduit.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldNomProduit.setPlaceholder("Nom de produit");
        jCTextFieldNomProduit.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jCTextFieldNomProduit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Qantité prod");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, -1));

        jCTextFieldQuantite.setBackground(new java.awt.Color(51, 0, 102));
        jCTextFieldQuantite.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldQuantite.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldQuantite.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldQuantite.setPlaceholder("Entrez la quantité des produit");
        jPanel2.add(jCTextFieldQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        rSMaterialButtonRectangleFermer.setText("Fermer");
        rSMaterialButtonRectangleFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleFermerActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangleFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 100, 40));

        rSMaterialButtonRectangleModifier.setText("Modifier");
        rSMaterialButtonRectangleModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleModifierActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangleModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, 40));

        rSMaterialButtonRectangleSupprimer.setText("Supprimer");
        rSMaterialButtonRectangleSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleSupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangleSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, 40));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 20, 40));

        jCTextFieldRecherche.setBackground(new java.awt.Color(51, 0, 102));
        jCTextFieldRecherche.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextFieldRecherche.setForeground(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setCaretColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextFieldRecherche.setPlaceholder("Rechercher un produit");
        jCTextFieldRecherche.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(jCTextFieldRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 150, -1));

        rSMaterialButtonRectangleRecherche.setText("Rechercher");
        rSMaterialButtonRectangleRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangleRechercheActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangleRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 350, 620));

        setSize(new java.awt.Dimension(940, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void rSMaterialButtonRectangleModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleModifierActionPerformed
        // TODO add your handling code here:
        Produit prod1=new Produit();
        if(jCTextFieldIdproduit.getText().length()>0){
            prod1.setId_prod(parseInt(jCTextFieldIdproduit.getText()));
        }
        if(jCTextFieldNomProduit.getText().length()>0){
            prod1.setNom_prod(jCTextFieldNomProduit.getText());
        }
        if(jCTextFieldQuantite.getText().length()>0){
            prod1.setQte_paye(parseInt(jCTextFieldQuantite.getText()));
        }
        int resultat=ServiceProduit.UpdateProduit(prod1);
        if(resultat==0){
            JOptionPane.showMessageDialog(rootPane,"Erreur de modification un probleme est surevenu!");
        }else{
            JOptionPane.showMessageDialog(rootPane,"Modification effectué avec succés");
        }
        
    }//GEN-LAST:event_rSMaterialButtonRectangleModifierActionPerformed

    private void rSMaterialButtonRectangleRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleRechercheActionPerformed
        // TODO add your handling code here:
        if(jCTextFieldRecherche.getText().length()>0){
            Produit ILveUBtia=ServiceProduit.ReadProduit(jCTextFieldRecherche.getText());
            if(ILveUBtia.getId_prod()==0){
                JOptionPane.showMessageDialog(rootPane,"Produit non trouvé revoyez le nom du produit", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            }else{
                jCTextFieldIdproduit.setText(String.valueOf(ILveUBtia.getId_prod()));
                jCTextFieldNomProduit.setText(ILveUBtia.getNom_prod());
                jCTextFieldQuantite.setText(String.valueOf(ILveUBtia.getQte_paye()));
               
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"le champs de recherche ne peut op etre nul pour pouvoir faire la recherche d'un produit", "information message", JOptionPane.INFORMATION_MESSAGE);
            jCTextFieldRecherche.requestFocus();
        }
        
        
    }//GEN-LAST:event_rSMaterialButtonRectangleRechercheActionPerformed

    private void rSMaterialButtonRectangleFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangleFermerActionPerformed

    private void rSMaterialButtonRectangleSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangleSupprimerActionPerformed
        // TODO add your handling code here:
        if(jCTextFieldRecherche.getText().length()>0){
            int choix=JOptionPane.showConfirmDialog(rootPane,"Voulez-vous vraiment supprimer ce produit?","COnfirmation Message",JOptionPane.YES_NO_OPTION);
            if(choix==0){
                int prod2=ServiceProduit.DeleteProduit(jCTextFieldRecherche.getText());
                if(prod2==0){
                    JOptionPane.showMessageDialog(rootPane,"Erreur sql revoir les parametres de la methode delete et l'execution","Warning messagr",JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Produit supprimer!","Information Message",JOptionPane.INFORMATION_MESSAGE);
                    jCTextFieldIdproduit.setText(null);
                    jCTextFieldRecherche.setText(null);
                    jCTextFieldRecherche.requestFocus();
                    jCTextFieldNomProduit.setText(null);
                    jCTextFieldQuantite.setText(null);
                }
            }
        }
    }//GEN-LAST:event_rSMaterialButtonRectangleSupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModifSupProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModifSupProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModifSupProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModifSupProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModifSupProduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextFieldIdproduit;
    private app.bolivia.swing.JCTextField jCTextFieldNomProduit;
    private app.bolivia.swing.JCTextField jCTextFieldQuantite;
    private app.bolivia.swing.JCTextField jCTextFieldRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleFermer;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleModifier;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleRecherche;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangleSupprimer;
    // End of variables declaration//GEN-END:variables
}
